---
- name: Generate mac addresses for control plane
  ansible.builtin.set_fact:
    ai_control_plane_macs: >
      {{ ai_control_plane_macs + ['f6' |
          community.general.random_mac(ai_ocp_namespace + _cluster_name + 'm1' + _index|string)] }}
    ai_control_plane_macs2: >
      {{ ai_control_plane_macs2 + ['f6' |
          community.general.random_mac(ai_ocp_namespace + _cluster_name + 'm2' + _index|string)] }}
  loop: "{{ range(1,control_plane_instance_count|int+1)|list }}"
  loop_control:
    loop_var: _index

- name: Generate MAC addresses for control plane for attached networks
  ansible.builtin.set_fact:
    ai_attach_control_plane_macs: >-
      {{
        ai_attach_control_plane_macs | combine({
          item.1: (ai_attach_control_plane_macs[item.1] | default([])) + [
            'f6' | community.general.random_mac(
              ai_ocp_namespace + _cluster_name + item.0|string + item.1
            )
          ]
        })
      }}
  loop: "{{ range(1, control_plane_instance_count | int + 1) | list | product(ai_attach_control_plane_networks) | list }}"
  loop_control:
    loop_var: item

- name: Generate mac addresses for workers
  ansible.builtin.set_fact:
    ai_workers_macs: >
        {{ ai_workers_macs + ['f6' |
            community.general.random_mac(ai_ocp_namespace + _cluster_name + 'w1' + _index|string)] }}
    ai_workers_macs2: >
        {{ ai_workers_macs2 + ['f6' |
            community.general.random_mac(ai_ocp_namespace + _cluster_name + 'w2' + _index|string)] }}
  loop: "{{ range(1,worker_instance_count|int+1)|list }}"
  loop_control:
    loop_var: _index

- name: Generate MAC addresses for workers for attached networks
  ansible.builtin.set_fact:
    ai_attach_workers_macs: >-
      {{
        ai_attach_workers_macs | combine({
          item.1: (ai_attach_workers_macs[item.1] | default([])) + [
            'f6' | community.general.random_mac(
              ai_ocp_namespace + _cluster_name + item.0|string + item.1
            )
          ]
        })
      }}
  loop: "{{ range(1, worker_instance_count | int + 1) | list | product(ai_attach_workers_networks) | list }}"
  loop_control:
    loop_var: item

- name: Set static_network_config variable
  ansible.builtin.set_fact:
    static_network_config: "{{ lookup('template','static_network_config_full.yaml.j2') | from_yaml }}"

- name: Extract openshift-install and generate ISO
  delegate_to: "{{ groups['bastions'][0] }}"
  block:
  - name: Install required nmstate package
    become: true
    ansible.builtin.yum:
      name: nmstate

  - name: Create /tmp/pull-secret.json
    ansible.builtin.copy:
      dest: "/tmp/pull-secret.json"
      content: "{{ ai_pull_secret | from_json }}"

# FIXME
  - name: Get version
    ansible.builtin.shell: /usr/bin/oc version -o json | jq -r ".releaseClientVersion"
    register: r_oc_version

  - name: Extract openshift-install binary
    become: true
    ansible.builtin.command: |
      /usr/bin/oc adm release extract --registry-config=/tmp/pull-secret.json --command=openshift-install --to /usr/bin/
      quay.io/openshift-release-dev/ocp-release:{{ r_oc_version.stdout }}-x86_64

  - name: Remove /tmp/pull-secret.json
    ansible.builtin.file:
      path: "/tmp/pull-secret.json"
      state: absent

  - name: Ensure {{ ansible_user }}/{{ cluster_name }}/ exists
    ansible.builtin.file:
      path: "~{{ ansible_user }}/{{ cluster_name }}/"
      state: directory

  - name: Ensure {{ ansible_user }}/{{ cluster_name }}/openshift/ exists
    ansible.builtin.file:
      path: "~{{ ansible_user }}/{{ cluster_name }}/openshift/"
      state: directory

  - name: Generate the install-config.yaml from mode-specific template
    ansible.builtin.template:
      src: "install-config-connected.yaml.j2"
      dest: "~{{ ansible_user }}/{{ cluster_name }}/install-config.yaml"

  - name: Generate the agent-config.yaml from template
    ansible.builtin.template:
      src: "agent-config.yaml.j2"
      dest: "~{{ ansible_user }}/{{ cluster_name }}/agent-config.yaml"

  - name: Add etcd manifest
    ansible.builtin.copy:
      src: "etcd_disk.yaml"
      dest: "~{{ ansible_user }}/{{ cluster_name }}/openshift/10-control-plane-etcd-config.yaml"

  - name: Add routers replicas manifest
    ansible.builtin.template:
      src: "router_replicas.yaml.j2"
      dest: "~{{ ansible_user }}/{{ cluster_name }}/openshift/99_router-replicas.yaml"

  - name: Add OVN-Kubernetes to switch to local gateway mode manifest
    ansible.builtin.copy:
      src: "network_config.yaml"
      dest: "~{{ ansible_user }}/{{ cluster_name }}/openshift/cluster-network-03-config.yml"

  - name: Enable ip_forwarding for control plane
    ansible.builtin.template:
      src: "sysctl_control_plane.yaml"
      dest: "~{{ ansible_user }}/{{ cluster_name }}/openshift/98_sysctl-control-plane.yaml"

  - name: Add node hint manifest for SNO
    when: control_plane_instance_count | int == 1
    ansible.builtin.template:
      src: "node_hint.yaml"
      dest: "~{{ ansible_user }}/{{ cluster_name }}/openshift/98_node-hint.yaml"

  - name: Add MachineConfig manifests to Assisted Installer
    when: ai_machineconfigs | default([]) | length > 0
    ansible.builtin.copy:
      content: "{{ item | to_yaml }}"
      dest: "~{{ ansible_user }}/{{ cluster_name }}/openshift/{{ item.metadata.name }}.yaml"
    loop: "{{ ai_machineconfigs }}"
    loop_control:
      label: "{{ item.metadata.name }}"                   # Clean logging output using the MachineConfig name

  - name: Generate the ISO image
    ansible.builtin.command:
      cmd: "/usr/bin/openshift-install agent create image --dir ~{{ ansible_user }}/{{ cluster_name }}/"

  - name: Download virtctl
    ansible.builtin.get_url:
      url: https://github.com/kubevirt/kubevirt/releases/download/v1.7.3/virtctl-v1.7.3-linux-amd64
      dest: /tmp/virtctl
      mode: '0644'
    register: r_virtctl
    until: r_virtctl is success
    retries: 5
    delay: 10

  - name: Install virtctl to /usr/bin
    become: true
    ansible.builtin.copy:
      src: /tmp/virtctl
      remote_src: true
      dest: /usr/bin/virtctl
      mode: '0755'
      owner: root
      group: root

  - name: Remove downloaded virtctl temp file
    ansible.builtin.file:
      state: absent
      path: /tmp/virtctl

  - name: Create a DataVolume
    ansible.builtin.command: |
      virtctl --server {{ sandbox_openshift_api_url }} --token {{ sandbox_openshift_api_token }}
      --namespace {{ sandbox_openshift_namespace }} image-upload dv installation-iso-{{ cluster_name }} --size=2Gi
      --image-path=/home/{{ ansible_user }}/{{ cluster_name }}/agent.x86_64.iso

- name: Create three control plane VMs for full cluster
  vars:
    vmname: "{{ ai_ocp_vmname_control_plane_prefix }}-{{ _index }}"
    network: "{{ cluster_name }}-openshift"
    network_name: "{{ ai_install_use_network | default(cluster_name + '-openshift') }}"
    pod_network: "192.168.{{ _index }}.0/24"
  ansible.builtin.include_tasks: kubevirt/create_control_plane_etcd.yaml
  loop: "{{ range(1,control_plane_instance_count | int+1) | list }}"
  loop_control:
    loop_var: _index

- name: Create {{ worker_instance_count }} worker VMs for full cluster
  vars:
    vmname: "{{ ai_ocp_vmname_worker_prefix }}-{{ _index }}"
    network: "{{ cluster_name}}-openshift"
    network_name: "{{ ai_install_use_network | default(cluster_name + '-openshift') }}"
    pod_network: "192.168.1{{ _index }}.0/24"
  ansible.builtin.include_tasks: kubevirt/create_workers.yaml
  loop: "{{ range(1,worker_instance_count | int+1) | list }}"
  loop_control:
    loop_var: _index

- name: Wait for three control plane VMs to be running
  vars:
    vmname: "{{ ai_ocp_vmname_control_plane_prefix }}-{{ _index }}"
  ansible.builtin.include_tasks: kubevirt/wait_control_plane_etcd.yaml
  loop: "{{ range(1,control_plane_instance_count | int+1) | list }}"
  loop_control:
    loop_var: _index

- name: Wait for {{ worker_instance_count }} worker VMs to be running
  vars:
    vmname: "{{ ai_ocp_vmname_worker_prefix }}-{{ _index }}"
  ansible.builtin.include_tasks: kubevirt/wait_workers.yaml
  loop: "{{ range(1,worker_instance_count | int+1) | list }}"
  loop_control:
    loop_var: _index

- name: Wait for complete installation
  delegate_to: "{{ groups['bastions'][0] }}"
  block:
    - name: Wait for bootstrap to be completed
      ansible.builtin.command: |
        /usr/bin/openshift-install --dir /home/{{ ansible_user }}/{{ cluster_name }}/ agent wait-for bootstrap-complete --log-level=debug

    - name: Wait for installation to be completed
      ansible.builtin.command: |
        /usr/bin/openshift-install --dir /home/{{ ansible_user }}/{{ cluster_name }}/ agent wait-for install-complete  --log-level=debug
