---
- name: Step 000 Pre Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
  - name: Print stage message
    ansible.builtin.debug:
      msg: "Step 000 Pre-Infrastructure"
