---
- name: Generate admin user password
  when: hcp_onprem_admin_password | default("") | length == 0
  ansible.builtin.set_fact:
    _hcp_onprem_admin_password: >-
      {{ lookup('password', '/dev/null chars=ascii_letters,digits '
          ~ 'length=' ~ hcp_onprem_admin_password_length) }}

- name: Set admin user password
  when: hcp_onprem_admin_password | default("") | length > 0
  ansible.builtin.set_fact:
    _hcp_onprem_admin_password: "{{ hcp_onprem_admin_password }}"

- name: Set up user passwords
  when: hcp_onprem_user_count | int > 0
  block:
    - name: Initialize user password list
      ansible.builtin.set_fact:
        _hcp_onprem_user_passwords: []

    - name: Generate randomized user passwords
      when: hcp_onprem_user_password | default("") | length == 0
      ansible.builtin.set_fact:
        _hcp_onprem_user_passwords: >-
          {{ _hcp_onprem_user_passwords + [lookup('password',
            '/dev/null chars=ascii_letters,digits '
            ~ 'length=' ~ hcp_onprem_user_password_length)] }}
      loop: "{{ range(0, hcp_onprem_user_count | int) | list }}"

    - name: Set common user passwords
      when: hcp_onprem_user_password | default("") | length > 0
      ansible.builtin.set_fact:
        _hcp_onprem_user_passwords: >-
          {{ _hcp_onprem_user_passwords + [hcp_onprem_user_password] }}
      loop: "{{ range(0, hcp_onprem_user_count | int) | list }}"

- name: Initialize empty user password list when no users
  when: hcp_onprem_user_count | int == 0
  ansible.builtin.set_fact:
    _hcp_onprem_user_passwords: []

- name: Create temporary htpasswd file
  ansible.builtin.tempfile:
    state: file
    suffix: htpasswd
  register: _hcp_onprem_htpasswd_file

- name: Add admin user to htpasswd file
  ansible.builtin.command: >-
    htpasswd -cbB {{ _hcp_onprem_htpasswd_file.path }}
    {{ hcp_onprem_admin_user }}
    {{ _hcp_onprem_admin_password }}
  changed_when: true

- name: Add users to htpasswd file
  when: hcp_onprem_user_count | int > 0
  ansible.builtin.command: >-
    htpasswd -bB {{ _hcp_onprem_htpasswd_file.path }}
    {{ hcp_onprem_user_base }}{{ item + 1 }}
    {{ _hcp_onprem_user_passwords[item] }}
  loop: "{{ range(0, hcp_onprem_user_count | int) | list }}"
  changed_when: true

- name: Read htpasswd file contents
  ansible.builtin.slurp:
    src: "{{ _hcp_onprem_htpasswd_file.path }}"
  register: _hcp_onprem_htpasswd_slurp

- name: Set htpasswd content fact
  ansible.builtin.set_fact:
    _hcp_onprem_htpasswd_content: "{{ _hcp_onprem_htpasswd_slurp['content'] }}"

- name: Remove temporary htpasswd file
  ansible.builtin.file:
    path: "{{ _hcp_onprem_htpasswd_file.path }}"
    state: absent

- name: Create htpasswd secret
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'secret-htpasswd.yaml.j2') | from_yaml }}"
