---
- name: Destroy sandbox environment
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
  - name: Set destroy workload list
    ansible.builtin.set_fact:
      _remove_workloads: >-
        {{ remove_workloads
           if (remove_workloads | default([]) | length > 0)
           else (workloads | default([]) | reverse | list) }}

  - name: Destroy workloads
    when: _remove_workloads | length > 0
    ansible.builtin.include_role:
      name: "{{ _workload }}"
    vars:
      ACTION: destroy
    loop: "{{ _remove_workloads }}"
    loop_control:
      loop_var: _workload
      label: "{{ _workload }}"
