---
- name: Step 000 Pre Infrastructure
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
  - name: Call Role to scale OpenShift using Assisted Installer
    when: openshift_cnv_scale_cluster | default(false) | bool
    ansible.builtin.include_role:
      name: host_ocp4_assisted_scale

  - name: Scale OpenShift workers on AWS
    when: openshift_aws_scale_cluster | default(false) | bool
    ansible.builtin.include_role:
      name: agnosticd.cloud_provider_aws.scale_ocp_workers

  - name: Create HCP cluster on on-prem CNV
    when: hcp_onprem_create_cluster | default(false) | bool
    ansible.builtin.include_role:
      name: host_ocp4_hcp_cnv_onprem_install
